// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Attempt struct {
	ID                   string    `json:"id"`
	SessionID            int64     `json:"session_id"`
	TargetNumber         int16     `json:"target_number"`
	NumOfDiceThrow       int16     `json:"num_of_dice_throw"`
	FirstDiceThrowValue  int16     `json:"first_dice_throw_value"`
	SecondDiceThrowValue int16     `json:"second_dice_throw_value"`
	CreatedAt            time.Time `json:"created_at"`
}

type Entry struct {
	ID       int64 `json:"id"`
	WalletID int64 `json:"wallet_id"`
	// can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID               int64          `json:"id"`
	CurrentAttemptID sql.NullString `json:"current_attempt_id"`
	Owner            string         `json:"owner"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Transfer struct {
	ID           int64 `json:"id"`
	FromWalletID int64 `json:"from_wallet_id"`
	ToWalletID   int64 `json:"to_wallet_id"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

type Wallet struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Asset     string    `json:"asset"`
	CreatedAt time.Time `json:"created_at"`
}
