// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	AddWalletBalance(ctx context.Context, arg AddWalletBalanceParams) (Wallet, error)
	CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, username string) (User, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeleteWallet(ctx context.Context, id int64) error
	EndUserGameSession(ctx context.Context, id int64) (Session, error)
	GetAttempt(ctx context.Context, id string) (Attempt, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetSession(ctx context.Context, id int64) (Session, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserTransactionLogs(ctx context.Context, username string) ([]GetUserTransactionLogsRow, error)
	GetUserWithSession(ctx context.Context, owner string) (GetUserWithSessionRow, error)
	GetWallet(ctx context.Context, id int64) (Wallet, error)
	GetWalletByUsername(ctx context.Context, owner string) (Wallet, error)
	GetWalletForUpdate(ctx context.Context, owner string) (Wallet, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	Listwallets(ctx context.Context, arg ListwalletsParams) ([]Wallet, error)
	UpdateNumOfDiceThrown(ctx context.Context, id string) (Attempt, error)
	UpdateSessionCurrentAttemptId(ctx context.Context, arg UpdateSessionCurrentAttemptIdParams) (Session, error)
	UpdateValueofFirstDiceThrown(ctx context.Context, arg UpdateValueofFirstDiceThrownParams) (Attempt, error)
	UpdateValueofSecondDiceThrown(ctx context.Context, arg UpdateValueofSecondDiceThrownParams) (Attempt, error)
	UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
